// Import mongoose for MongoDB schema and model creation
import mongoose from "mongoose";

// Blog schema definition
const blogformSchema = new mongoose.Schema(
  {
    // 📝 Blog title
    title: {
      type: String, // Title must be text
      required: true, // Cannot save blog without a title
      trim: true, // Removes extra spaces from start & end
    },

    // 📄 Blog content
    // Stored as HTML generated by TipTap editor
    description: {
      type: String, // Rich text stored as HTML
      required: true, // Blog content is mandatory
    },

    // 🏷️ Blog tags (comma-separated string)
    tags: {
      type: String, // Tags stored as plain text
      required: true, // Tags are required
      trim: true, // Clean unnecessary spaces
    },

    // 🔐 Author reference
    // Links each blog to the logged-in user
    author: {
      type: mongoose.Schema.Types.ObjectId, // MongoDB ObjectId
      ref: "SignUpData", // Reference to users collection
      required: true, // Blog must have an author
    },
  },
  {
    // ⏱ Automatically adds:
    // createdAt → when blog was created
    // updatedAt → when blog was last modified
    timestamps: true,
  }
);

// Export the Blog model
// "BlogFormData" becomes the MongoDB collection name (blogsformdatas)
export default mongoose.model("BlogFormData", blogformSchema);
